DROP SEQUENCE REPLYSEQ;
DROP TABLE REPLY;

CREATE SEQUENCE REPLYSEQ;
CREATE TABLE REPLY(
	REPLY_NO NUMBER PRIMARY KEY,
	BOARD_NO NUMBER REFERENCES BOARD(BOARD_NO),
	MEMBER_ID VARCHAR2(300),
	REPLY_CONTENT VARCHAR2(500),
	REPLY_REGDATE DATE,
	REPLY_UPDATEDATE DATE
);

SELECT *
FROM REPLY
ORDER BY REPLY_NO DESC;