DROP TABLE BOARD;
DROP SEQUENCE BOARDSEQ;

CREATE SEQUENCE BOARDSEQ;

CREATE TABLE BOARD(
	BOARD_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER,
	BOARD_CONTENT VARCHAR2(500),
	BOARD_HASHTAG VARCHAR2(200),
	BOARD_LIKE VARCHAR2(20),
	BOARD_PRIVACY VARCHAR2(2) DEFAULT 'Y',
	BOARD_REGDATE DATE,
	BOARD_UPDATEDATE DATE,
	
	CONSTRAINT BOARD_NO_PK PRIMARY KEY(BOARD_NO),
	CONSTRAINT PRIVACY_CHECK CHECK(BOARD_PRIVACY IN('Y','N'))
)
--4

SELECT * FROM BOARD
ORDER BY BOARD_NO DESC;



select m.member_name,m.member_profile,m.member_no ,b.board_content,b.board_regdate,f.files_no ,f.FILES_URL 
from member m join board  b on m.member_no = b.member_no  join files f on b.board_no = f.board_no
where b.board_no =1

