
DROP TABLE DAILYFOODRECORD;

CREATE TABLE DAILYFOODRECORD(
	MEMBER_NO NUMBER PRIMARY KEY,
	CALENDAR_DATE DATE,
	FOOD_NO NUMBER,
	INTAKE_KCAL NUMBER,
	CONSTRAINT DAILYFOODRECORD_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
	CONSTRAINT DAILYFOODRECORD_FOOD_NO_FK FOREIGN KEY (FOOD_NO) REFERENCES FOODDB(FOOD_NO)
)
