CREATE TABLE DAILYEXERCISERECORD(
	MEMBER_NO NUMBER,
	CALENDAR_DATE DATE,
	COURSE_NAME VARCHAR2(20),
	BURN_KCAL NUMBER,
	DISTANCE NUMBER,
	CONSTRAINT DAILYEXERCISERECORD_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
)

