CREATE TABLE DAILYFOODRECORD(
	MEMBER_NO NUMBER PRIMARY KEY,
	CALENDAR_DATE DATE,
	FOOD_NO NUMBER,
	FOOD_NAME VARCHAR2(20),
	INTAKE_KCAL NUMBER,
	CONSTRAINT DAILYFOODRECORD_MEMBER_NO_FK FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
)