/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.39
 * Generated at: 2021-01-04 21:40:10 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.bs.dabom.model.dto.Member_Dto;

public final class frienddetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/header.jsp", Long.valueOf(1609794071000L));
    _jspx_dependants.put("jar:file:/Users/seowonchoi/Documents/finalproject/BrightSiblings/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/BrightSiblings/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/insertdonation.jsp", Long.valueOf(1608053833000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1607496808000L));
    _jspx_dependants.put("/WEB-INF/views/updatemember.jsp", Long.valueOf(1609669677000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bs.dabom.model.dto.Member_Dto");
    _jspx_imports_classes.add("java.util.List");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write(" \n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 님의 페이지 입니다. </title>\n");
      out.write('\n');

	response.setHeader("Pragma", "no-cache");
response.setHeader("Cache-Control", "no-cache");
response.setHeader("Cache-Control", "no-store");
response.setDateHeader("Expires", 0L);

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<!-- 파비콘-->\n");
      out.write("<link rel=\"shortcut icon\" href=\"resources/image/cherry-blossom.png\">\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/header.css\" />\n");
      out.write("<title>DABOM, 다이어트의 봄</title>\n");
      out.write("<link\n");
      out.write("\thref=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css\"\n");
      out.write("\trel=\"stylesheet\" id=\"bootstrap-css\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\"></script>\n");
      out.write("<script\n");
      out.write("\tsrc=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\"\n");
      out.write("\tintegrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\"\n");
      out.write("\tintegrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\"\n");
      out.write("\tcrossorigin=\"anonymous\">\n");
      out.write("<script\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css\">\n");
      out.write("<script type=\"text/javascript\"\n");
      out.write("\tsrc=\"https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.js\"></script>\n");
      out.write("<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js'></script>\n");
      out.write("<script src='https://stackpath.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.bundle.min.js'></script>\n");
      out.write("<!-- 아이콘 -->\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t\n");
      out.write("\t<header>\n");
      out.write("\t\t<nav>\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t <li><a href=\"mainpage.do\" id=\"dabom\"><img style=\"width:30px;height:30px;\" alt=\"로고\" src=\"resources/image/cherry-blossom.png\"/> </a> </li>\n");
      out.write("                <li id=\"search_wrapper\">  \n");
      out.write("                <input type=\"text\" class=\"search-input\" placeholder=\"검색\" />\n");
      out.write("                <button id=\"search_btn\" onclick=\"search();\" class=\"tooltip-\" > <i class=\"fas fa-search\"></i> </button> \n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("\t\t\t\t<li id=\"space2\"></li>\n");
      out.write("\n");
      out.write("\t\t        <li> <a class=\"toltip center-icon\" data-tooltip=\"Home\" href=\"mainpage.do\" id=\"home\"> <i class=\"fas fa-home\"></i> </a> </li>\n");
      out.write("\t\t        <li> <a class=\"toltip center-icon\" data-tooltip=\"NEWS\" href=\"news.do\" id=\"group\"> <i class=\"far fa-newspaper\"></i> </a></li>\n");
      out.write("                <li> <a class=\"toltip center-icon\" data-tooltip=\"FoodDictionary\" href=\"foodlist.do\" id=\"calories\"> <i class=\"fas fa-utensils\"></i> </a> </li>\n");
      out.write("                <li> <a class=\"toltip center-icon\" data-tooltip=\"Youtube\" href=\"youtube.do\" id=\"youtube\"> <i class=\"fab fa-youtube\"></i> </a> </li>\n");
      out.write("\n");
      out.write("\t\t\t\t<li id=\"space1\"></li>\n");
      out.write("\t\t\t\t<li><a>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 반갑습니다.</a></li>\n");
      out.write("\t\t\t\t<li><a href=\"mypage_main.do\" class=\"toltip\" data-tooltip=\"MYPAGE\" id=\"btn_plus\"><img \tstyle=\"width: 40px; height: 40px;\" class=\"profileimg\" alt=\"프로필사진\"  src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_profile }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></a></li>\n");
      out.write("\t\t\t\t<li><a class=\"toltip\" data-tooltip=\"Message\" id=\"btn_msg\"><i class=\"fab fa-facebook-messenger\"></i></a></li> \t\t\n");
      out.write("<!-- \t\t\t\t<li><a class=\"toltip\" data-tooltip=\"Notification\"  id=\"btn_bell\"> <i class=\"fas fa-bell\"></i> <span \tclass=\"noti-badge \"></span></a></li> -->\n");
      out.write("\t\t\t\t<li><a class=\"toltip\" data-tooltip=\"Settings\" id=\"btn_profile\"><i class=\"fas fa-cog\"></i></a></li> \n");
      out.write("\t\t\t\t<li><a class=\"toltip\" data-tooltip=\"Donation\" id=\"btn_donation\"><i class=\"fas fa-hand-holding-usd\"></i></a></li>\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<ul id=\"hide\" class=\"hide\">\n");
      out.write("\t\t\t\t<li><a onclivk=\"location.href='logout.do'\" class=\"hidecontent\"><i class=\"fas fa-sign-out-alt\"></i>로그아웃</a></li>\n");
      out.write("\t\t\t\t<li><a onclick=\"updatemember();\" class=\"hidecontent\"><i class=\"fas fa-user-edit\"></i>회원수정</a></li>\n");
      out.write("\t\t\t\t<li><a onclick=\"deletemember();\" class=\"hidecontent\"><i\tclass=\"fas fa-user-minus\"></i>회원탈퇴</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<div id=\"msg-hide\" class=\"msg-hide\" >\n");
      out.write("\t\t\t\t<div class=\"container-fluid h-100\">\n");
      out.write("\t\t\t<div class=\"row justify-content-center h-100\">\n");
      out.write("\t\t\t\t<div class=\"chat\"><div class=\"card  contacts_card\">\n");
      out.write("\t\t\t\t\t<div class=\"card-header\">\n");
      out.write("\t\t\t\t\t\t<div class=\"input-group\">\n");
      out.write("\t\t\t\t\t\t\t<input type=\"text\" placeholder=\"Search...\" name=\"\" class=\"form-control search\">\n");
      out.write("\t\t\t\t\t\t\t<div class=\"input-group-prepend\">\n");
      out.write("\t\t\t\t\t\t\t\t<span class=\"input-group-text search_btn\"><i class=\"fas fa-search\"></i></span>\n");
      out.write("\t\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"card-body contacts_body\" style=\"overflow: scroll;\">\n");
      out.write("\t\t\t\t\t\t<ul class=\"contacts\">\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t</ul>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("               \n");
      out.write("               \n");
      out.write("               </div>\n");
      out.write("           \n");
      out.write("\t\t\t<div id=\"search-hide\" class=\"search-hide\">\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t</header>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl: \"chatroomlist.do?member_no=\"+ ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(",\n");
      out.write("\t\t\t\ttype : \"GET\",\n");
      out.write("\t\t\t\tsuccess :function(data){\n");
      out.write("\t\t\t\t\tif(data.check ==false|| data.chatroomlist ==null){\n");
      out.write("\t\t\t\t\t\tvar nomessage = \"<div>채팅이 없네요 시작해보세용!!</div>\"\n");
      out.write(" \t\t\t\t\t\t$(\".contacts\").after(nomessage);\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\tvar chatroomlistarr = data.chatroomlist;\n");
      out.write("\t\t\t\t\t\tvar chatroomList =\"\";\n");
      out.write("\t\t\t\t\t\tfor(var i = 0; i < chatroomlistarr.length; i++){\n");
      out.write("\t\t\t\t\t\t\tchatroomList +=\"<li><a onclick=\"+\"\\\"window.open\"+\"('chatmsglist.do?chatroom_no=\"+chatroomlistarr[i].chatroom_no+\"','popup','width=500px,height=530px')\\\"\"+\" style='text-decoration:none; color:black; '><div class='d-flex bd-highlight'><div class='img_cont'><img src='\"+\n");
      out.write("\t\t\t\t\t\t\tchatroomlistarr[i].member_profile+\"' class='rounded-circle user_img'></div><div class='user_info'><span>\"+chatroomlistarr[i].member_name+\"</span><p>\"+\n");
      out.write("\t\t\t\t\t\t\tchatroomlistarr[i].last_message+\"</p><p>\"+chatroomlistarr[i].sendingtime+\n");
      out.write("\t\t\t\t\t\t\t\"</p></div></div></a></li>\";\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t$(\".contacts\").html(chatroomList);\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},error:function(err){\n");
      out.write("\t\t\t\t\tconsole.log(err );\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t})\n");
      out.write("\t\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\tfunction search() {\n");
      out.write("\t\t\tvar keyword = $(\".search-input\").val();\n");
      out.write("\t\t\tif (keyword == '') {\n");
      out.write("\t\t\t\t$(\"#search-hide\").html('<p>검색어를 입력해 주세요</p>');\n");
      out.write("\t\t\t} else {\n");
      out.write("\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\t\t\turl : \"search.do?keyword=\" + keyword,\n");
      out.write("\t\t\t\t\t\t\ttype : \"GET\",\n");
      out.write("\t\t\t\t\t\t\tsuccess : function(data) {\n");
      out.write("\t\t\t\t\t\t\t\tif (data.check == \"OK\") {\n");
      out.write("\t\t\t\t\t\t\t\t\tvar arr = data.searchlist;\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(arr);\n");
      out.write("\t\t\t\t\t\t\t\t\tvar searchlist = '';\n");
      out.write("\t\t\t\t\t\t\t\t\tfor (var i = 0; i < arr.length; i++) {\n");
      out.write("\t\t\t\t\t\t\t\t\t\tsearchlist += \"<p class='search-res'><img class='search-img'  style='width:40px;height:40px;border-radius:50% 50%;' src='\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ arr[i].member_profile\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"' alt='프로필사진'/><a class='search-a' href=\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"'friendDetail.do?member_no=\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ arr[i].member_no\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"'><span>\"\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ arr[i].member_name\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t+ \"<i class='fas fa-arrow-alt-circle-right'></i></span></a><p>\";\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\t\t\tconsole.log(searchlist);\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#search-hide\").html(searchlist);\n");
      out.write("\t\t\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\t\t\tvar searchlist = \"<p>검색하신 조건으로 조회된 결과가 없습니다.</p>\"\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#search-hide\").html(searchlist);\n");
      out.write("\t\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\t\t\terror : function(err) {\n");
      out.write("\t\t\t\t\t\t\t}\n");
      out.write("\n");
      out.write("\t\t\t\t\t\t});\n");
      out.write("\n");
      out.write("\t\t\t}\n");
      out.write("\n");
      out.write("\t\t}\n");
      out.write("/* \n");
      out.write("\t\t$(\"#search_btn\").click(function() {\n");
      out.write("\t\t\t$(\".search-hide\").stop().slideDown(500);\n");
      out.write("\t\t\treturn false; \n");
      out.write("\t\t});\n");
      out.write("\t\t$(document).click(function(e) {\n");
      out.write("\t\t\tif (e.target.className == \"search-hide\") {\n");
      out.write("\t\t\t\treturn false\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$(\".search-hide\").stop().slideUp(500);\n");
      out.write("\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$(\"#btn_profile\").click(function() {\n");
      out.write("\t\t\t$(\"#hide\").stop().slideDown(500);\n");
      out.write("\t\t\treturn false; \n");
      out.write("\t\t});\n");
      out.write("\t\t$(document).click(function(e) {\n");
      out.write("\t\t\tif (e.target.className == \"hide\") {\n");
      out.write("\t\t\t\treturn false\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$(\"#hide\").stop().slideUp(500);\n");
      out.write("\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t\t$(\"#btn_msg\").click(function() {\n");
      out.write("\t\t\t$(\"#msg-hide\").stop().slideDown(500);\n");
      out.write("\t\t\treturn false; \n");
      out.write("\t\t});\n");
      out.write("\t\t$(document).click(function(e) {\n");
      out.write("\t\t\tif (e.target.className == \"msg-hide\") {\n");
      out.write("\t\t\t\treturn false\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t$(\"#msg-hide\").stop().slideUp(500);\n");
      out.write("\n");
      out.write("\t\t}); */\n");
      out.write("\n");
      out.write("\t\t/* \tvar hoverbtn = document.getElementById(\"btn_profile\");\n");
      out.write("\t\t hoverbtn.addEventListener(\"click\",function(){\n");
      out.write("\t\t var hideul = document.getElementById(\"hide\");\n");
      out.write("\n");
      out.write("\t\t if(hideul.style.display=='none'){\n");
      out.write("\t\t hideul.style.display='block';\n");
      out.write("\t\t }else{\n");
      out.write("\t\t hideul.style.display='none'\n");
      out.write("\t\t } \n");
      out.write("\t\t }); */\n");
      out.write("\t\t \n");
      out.write("\n");
      out.write("\t\t$(document).ready(function() {\n");
      out.write("\t\t\tvar jbOffset = $('header').offset();\n");
      out.write("\t\t\t$(window).scroll(function() {\n");
      out.write("\t\t\t\tif ($(document).scrollTop() > jbOffset.top) {\n");
      out.write("\t\t\t\t\t$('header').addClass('headerFixed');\n");
      out.write("\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t$('header').removeClass('headerFixed');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\tfunction deletemember() {\n");
      out.write("\t\t\tvar checkdelete = confirm(\"정말로 삭제하시겠습니까?\");\n");
      out.write("\t\t\tvar member_no = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("\t\t\tvar loginValue = {\n");
      out.write("\t\t\t\t\"member_no\" : member_no\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\tconsole.log(member_no)\n");
      out.write("\n");
      out.write("\t\t\tif (checkdelete) {\n");
      out.write("\t\t\t\t$.ajax({\n");
      out.write("\t\t\t\t\ttype : \"post\",\n");
      out.write("\t\t\t\t\turl : \"/dabom/delete.do\",\n");
      out.write("\t\t\t\t\tdata : JSON.stringify(loginValue),\n");
      out.write("\t\t\t\t\tcontentType : \"application/json\",\n");
      out.write("\t\t\t\t\tsuccess : function(msg) {\n");
      out.write("\t\t\t\t\t\tif (msg.check > 0) {\n");
      out.write("\t\t\t\t\t\t\talert(\"이용해주셔서 감사합니다.회원탈퇴 성공하셨습니다.\");\n");
      out.write("\t\t\t\t\t\t\tlocation.href = \"login.do\";\n");
      out.write("\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\talert(\"다시 시도해주세요\")\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t},\n");
      out.write("\t\t\t\t\terror : function(msg) {\n");
      out.write("\t\t\t\t\t\tconsole.log(msg);\n");
      out.write("\t\t\t\t\t\talert(\"통신 실패\");\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t}\n");
      out.write("\t\t}\n");
      out.write("\t</script>\n");
      out.write("\t\t");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>업뎃창 </title>\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/updatemember.css\">\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<!-- 팝업 시작 -->\n");
      out.write("\t<div class=\"wrapper bg-white mt-sm-5\" id=\"update_popup\" style=\"display: none;\">\n");
      out.write("    <h1 class=\"pb-4 border-bottom\">회원정보 수정</h1>\n");
      out.write("    <div class=\"py-2\">\n");
      out.write("        <div class=\"row py-2\">\n");
      out.write("            <div class=\"col-md-6\"> <label for=\"firstname\">이름</label> <input type=\"text\" class=\"bg-light form-control\" id=\"member_name\" name=\"member_name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" readonly=\"readonly\"> </div>\n");
      out.write("            <div class=\"col-md-6\"> <label for=\"firstname\">생년월일</label> <input type=\"text\" class=\"bg-light form-control\" id=\"member_birthday\" name=\"member_birthday\"  value= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_birthday }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" > </div>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"row py-2\">\n");
      out.write("            <div class=\"col-md-6\"> <label for=\"email\">이메일 주소</label> <input type=\"text\" class=\"bg-light form-control\" id=\"member_email\" name=\"member_email\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </div>\n");
      out.write("            <div class=\"col-md-6 pt-md-0 pt-3\"> <label for=\"phone\">휴대폰번호</label> <input type=\"tel\" class=\"bg-light form-control\" id=\"member_phone\" name=\"member_phone\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_phone }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </div>\n");
      out.write("        </div>\n");
      out.write("     \t<div class=\"row py-2\">\n");
      out.write("            <div class=\"col-md-6\"> <label for=\"email\">주소</label> <input type=\"text\" class=\"bg-light form-control\" placeholder=\"우편번호\"  value= \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_zipcode  }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"name=\"member_zipcode\" id=\"member_zipcode\"  readonly=\"readonly\">\n");
      out.write("            <button type=\"button\" class=\"btn btn-outline-secondary\" onclick=\"execPostCode();\"><i class=\"fa fa-search\"></i> 우편번호 찾기</button> </div>\n");
      out.write("              <div class=\"col-md-12\"> <label for=\"phone\">도로명 주소</label> <input type=\"tel\" class=\"bg-light form-control\" name=\"member_firstaddr\" id=\"member_firstaddr\"  readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_firstaddr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </div>\n");
      out.write("            <div class=\"col-md-12\"> <label for=\"phone\">상세 주소</label> <input type=\"tel\" class=\"bg-light form-control\" name=\"member_secondaddr\" id=\"member_secondaddr\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_secondaddr }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> </div>\n");
      out.write("        </div>\n");
      out.write(" \n");
      out.write("        <div class=\"py-3 pb-4 border-bottom\"> <button class=\"updatesubmitbtn btn btn-danger mr-3\">정보 수정 저장</button> <button onclick=\"close_updatepopup();\" class=\"btn border button\">취소</button> </div>\n");
      out.write("        \n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\t<div class=\"update_background\"></div>\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("\tvar member_name ,member_birthday,member_email,member_phone,member_zipcode,member_firstaddr,member_secondaddr;\n");
      out.write("\tmember_no= ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(";\n");
      out.write("\tmember_name = $('#member_name').val().trim();\n");
      out.write("\tmember_birthday= $('#member_birthday').val().trim();\n");
      out.write("\tmember_email = $('#member_email').val().trim();\n");
      out.write("\tmember_phone= $('#member_phone').val().trim();\n");
      out.write("\tmember_zipcode = $('#member_zipcode').val().trim();\n");
      out.write("\tmember_firstaddr=$('#member_firstaddr').val().trim();\n");
      out.write("\t\tmember_secondaddr=$('#member_secondaddr').val().trim();\n");
      out.write("\t\n");
      out.write("\t$('#member_name').val \n");
      out.write("\t\n");
      out.write("\tvar updateValue ={\n");
      out.write("\t\t\t'member_no' : member_no,\n");
      out.write("\t\t\t'member_name': member_name,\n");
      out.write("\t\t\t'member_birthday': member_birthday,\n");
      out.write("\t\t\t'member_email' :member_email ,\n");
      out.write("\t\t\t'member_phone': member_phone, \n");
      out.write("\t\t\t'member_zipcode': member_zipcode, \n");
      out.write("\t\t\t'member_firstaddr': member_firstaddr,\n");
      out.write("\t\t\t'member_secondaddr': member_secondaddr\t\t\t\t\t\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t$('.updatesubmitbtn').click(function(){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl: 'updatemember.do' ,\n");
      out.write("\t\t\t\ttype: 'POST',\n");
      out.write("\t\t\t\tdata : JSON.stringify(updateValue),\n");
      out.write("\t\t\t\tcontentType : \"application/json\",\n");
      out.write("\t\t\t\tsuccess: function(msg){\n");
      out.write("\t\t\t\t\tif(msg.result=='OK'){\n");
      out.write("\t\t\t\t\t\talert('회원정보 수정 완료되었습니다. ');\n");
      out.write("\t\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t\talert('회원정보 하는 도중 문제가 발생하였네요..\\n 다시 시도해 주세요 !')\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror: function(err){\n");
      out.write("\t\t\t\t\talert('업데이트 실패하였습니다.다시 시도해 주세요!');\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t//클릭시 팝업창 닫기\n");
      out.write("\t\tfunction close_updatepopup(){\n");
      out.write("\t\t\t$(\"#update_popup\").hide();\n");
      out.write("\t\t\t$('.update_background').hide();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\tvar member_no = $(\"input[name='member_no']\").val;\n");
      out.write("\t\tfunction updatemember(){\n");
      out.write("\t\t\t$(\"#update_popup\").show();\n");
      out.write("\t\t\t$('.update_background').show();\n");
      out.write("\t\t\t\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t\n");
      out.write("\t\tvar empJ = /\\s/g;\n");
      out.write("\t\t// 이름 정규식 \n");
      out.write("\t\tvar nameJ = /^[가-힣]{2,4}|[a-zA-Z]{2,10}\\s[a-zA-Z]{2,10}$/;\n");
      out.write("\t\t// 이메일 검사 정규식 \n");
      out.write("\t\tvar mailJ = /^[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*@[0-9a-zA-Z]([-_.]?[0-9a-zA-Z])*.[a-zA-Z]{2,3}$/i;\n");
      out.write("\t\t// 휴대폰 번호 정규식 \n");
      out.write("\t\tvar phoneJ = /^01([0|1|6|7|8|9]?)?([0-9]{3,4})?([0-9]{4})$/;\n");
      out.write("\n");
      out.write("\t\tvar birthJ = false;\n");
      out.write("\t\t\n");
      out.write("\t\t$('form').on('submit', function () {\n");
      out.write("\t\t        var inval_Arr = new Array(4).fill(false);\n");
      out.write("\t\t       \n");
      out.write("\t\t      \n");
      out.write("\t\t        // 생년월일 정규식 \n");
      out.write("\t\t        if (birthJ) {\n");
      out.write("\t\t            console.log(birthJ);\n");
      out.write("\t\t            inval_Arr[0] = true;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            inval_Arr[0] = false;\n");
      out.write("\t\t            alert('생년월일을 확인하세요.');\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        }\n");
      out.write("\t\t        // 이메일 정규식 \n");
      out.write("\t\t        if (mailJ.test($('#member_email').val())) {\n");
      out.write("\t\t            console.log(phoneJ.test($('#member_email').val()));\n");
      out.write("\t\t            inval_Arr[1] = true;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            inval_Arr[1] = false;\n");
      out.write("\t\t            alert('이메일을 확인하세요.');\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        }\n");
      out.write("\t\t        // 휴대폰번호 정규식 \n");
      out.write("\t\t        if (phoneJ.test($('#member_phone').val())) {\n");
      out.write("\t\t            console.log(phoneJ.test($('#member_phone').val()));\n");
      out.write("\t\t            inval_Arr[2] = true;\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            inval_Arr[2] = false;\n");
      out.write("\t\t            alert('휴대폰 번호를 확인하세요.');\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        }\n");
      out.write("\t\t       \n");
      out.write("\t\t        //주소확인 \n");
      out.write("\t\t        if (address.val() == '') {\n");
      out.write("\t\t            inval_Arr[3] = false;\n");
      out.write("\t\t            alert('주소를 확인하세요.');\n");
      out.write("\t\t            return false;\n");
      out.write("\t\t        } else inval_Arr[3] = true;\n");
      out.write("\t\t        //전체 유효성 검사 \n");
      out.write("\t\t        var validAll = true;\n");
      out.write("\t\t        for (var i = 0; i < inval_Arr.length; i++) {\n");
      out.write("\t\t            if (inval_Arr[i] == false) {\n");
      out.write("\t\t                validAll = false;\n");
      out.write("\t\t            }\n");
      out.write("\t\t        }\n");
      out.write("\t\t        if (validAll == true) {\n");
      out.write("\t\t            // 유효성 모두 통과 \n");
      out.write("\t\t            alert('감사합니다.');\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            alert('정보를 다시 확인하세요.')\n");
      out.write("\t\t        }\n");
      out.write("\t\t    });\n");
      out.write("\n");
      out.write("\t\t   \n");
      out.write("\t\t   \n");
      out.write("\t\t    \n");
      out.write("\t\t  \n");
      out.write("\t\t    $(\"#member_email\").blur(function () {\n");
      out.write("\t\t        if (mailJ.test($(this).val())) {\n");
      out.write("\t\t            $(\"#email_check\").text('');\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $('#email_check').text('이메일 양식을 확인해주세요.');\n");
      out.write("\t\t            $('#email_check').css('color', 'red');\n");
      out.write("\t\t        }\n");
      out.write("\t\t    });\n");
      out.write("\t\t    // 생일 유효성 검사 \n");
      out.write("\t\t    var birthJ = false;\n");
      out.write("\t\t    // 생년월일 birthJ 유효성 검사 \n");
      out.write("\t\t    $('#member_birthday').blur(function () {\n");
      out.write("\t\t        var dateStr = $(this).val();\n");
      out.write("\t\t        var year = Number(dateStr.substr(0, 4));\n");
      out.write("\t\t        // 입력한 값의 0~4자리까지 (연) \n");
      out.write("\t\t        var month = Number(dateStr.substr(4, 2));\n");
      out.write("\t\t        // 입력한 값의 4번째 자리부터 2자리 숫자 (월) \n");
      out.write("\t\t        var day = Number(dateStr.substr(6, 2));\n");
      out.write("\t\t        // 입력한 값 6번째 자리부터 2자리 숫자 (일) \n");
      out.write("\t\t        var today = new Date();\n");
      out.write("\t\t        // 날짜 변수 선언 \n");
      out.write("\t\t        var yearNow = today.getFullYear();\n");
      out.write("\t\t        // 올해 연도 가져옴 \n");
      out.write("\t\t        if (dateStr.length <= 8) {\n");
      out.write("\t\t            // 연도의 경우 1900 보다 작거나 yearNow 보다 크다면 false를 반환합니다. \n");
      out.write("\t\t            if (year > yearNow || year < 1900) {\n");
      out.write("\t\t                $('#birth_check').text('생년월일을 확인해주세요');\n");
      out.write("\t\t                $('#birth_check').css('color', 'red');\n");
      out.write("\t\t            } else if (month < 1 || month > 12) {\n");
      out.write("\t\t                $('#birth_check').text('생년월일을 확인해주세요 ');\n");
      out.write("\t\t                $('#birth_check').css('color', 'red');\n");
      out.write("\t\t            } else if (day < 1 || day > 31) {\n");
      out.write("\t\t                $('#birth_check').text('생년월일을 확인해주세요 ');\n");
      out.write("\t\t                $('#birth_check').css('color', 'red');\n");
      out.write("\t\t            } else if ((month == 4 || month == 6 || month == 9 || month == 11) && day == 31) {\n");
      out.write("\t\t                $('#birth_check').text('생년월일을 확인해주세요 ');\n");
      out.write("\t\t                $('#birth_check').css('color', 'red');\n");
      out.write("\t\t            } else if (month == 2) {\n");
      out.write("\t\t                var isleap = (year % 4 == 0 && (year % 100 != 0 || year % 400 == 0));\n");
      out.write("\t\t                if (day > 29 || (day == 29 && !isleap)) {\n");
      out.write("\t\t                    $('#birth_check').text('생년월일을 확인해주세요 ');\n");
      out.write("\t\t                    $('#birth_check').css('color', 'red');\n");
      out.write("\t\t                } else {\n");
      out.write("\t\t                    $('#birth_check').text('');\n");
      out.write("\t\t                    birthJ = true;\n");
      out.write("\t\t                }\n");
      out.write("\t\t            } else {\n");
      out.write("\t\t                $('#birth_check').text('');\n");
      out.write("\t\t                birthJ = true;\n");
      out.write("\t\t            }\n");
      out.write("\t\t            //end of if \n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            //1.입력된 생년월일이 8자 초과할때 : auth:false \n");
      out.write("\t\t            $('#birth_check').text('생년월일을 확인해주세요 ');\n");
      out.write("\t\t            $('#birth_check').css('color', 'red');\n");
      out.write("\t\t        }\n");
      out.write("\t\t    }); //End of method \n");
      out.write("\t\t    // 휴대전화 \n");
      out.write("\t\t    $('#member_phone').blur(function () {\n");
      out.write("\t\t        if (phoneJ.test($(this).val())) {\n");
      out.write("\t\t            console.log(nameJ.test($(this).val()));\n");
      out.write("\t\t            $(\"#phone_check\").text('');\n");
      out.write("\t\t        } else {\n");
      out.write("\t\t            $('#phone_check').text('휴대폰번호를 확인해주세요 ');\n");
      out.write("\t\t            $('#phone_check').css('color', 'red');\n");
      out.write("\t\t        }\n");
      out.write("\t\t    });\n");
      out.write("\t\n");
      out.write("\t\t//우편번호 찾기 버튼 클릭시 발생 이벤트 \n");
      out.write("\t\tfunction execPostCode() {\n");
      out.write("\t\t    new daum.Postcode({\n");
      out.write("\t\t        oncomplete: function (data) {\n");
      out.write("\t\t            // 팝업에서 검색결과 항목을 클릭했을때 실행할 코드를 작성하는 부분. \n");
      out.write("\t\t            // 도로명 주소의 노출 규칙에 따라 주소를 조합한다. \n");
      out.write("\t\t            // 내려오는 변수가 값이 없는 경우엔 공백('')값을 가지므로, 이를 참고하여 분기 한다. \n");
      out.write("\t\t            var fullRoadAddr = data.roadAddress;\n");
      out.write("\t\t            // 도로명 주소 변수 \n");
      out.write("\t\t            var extraRoadAddr = '';\n");
      out.write("\t\t            // 도로명 조합형 주소 변수 \n");
      out.write("\t\t            // 법정동명이 있을 경우 추가한다. (법정리는 제외) \n");
      out.write("\t\t            // 법정동의 경우 마지막 문자가 \"동/로/가\"로 끝난다. \n");
      out.write("\t\t            if (data.bname !== '' && /[동|로|가]$/g.test(data.bname)) {\n");
      out.write("\t\t                extraRoadAddr += data.bname;\n");
      out.write("\t\t            }\n");
      out.write("\t\t            // 건물명이 있고, 공동주택일 경우 추가한다. \n");
      out.write("\t\t            if (data.buildingName !== '' && data.apartment === 'Y') {\n");
      out.write("\t\t                extraRoadAddr += (extraRoadAddr !== '' ? ', ' + data.buildingName : data.buildingName);\n");
      out.write("\t\t            }\n");
      out.write("\t\t            // 도로명, 지번 조합형 주소가 있을 경우, 괄호까지 추가한 최종 문자열을 만든다. \n");
      out.write("\t\t            if (extraRoadAddr !== '') {\n");
      out.write("\t\t                extraRoadAddr = ' (' + extraRoadAddr + ')';\n");
      out.write("\t\t            }\n");
      out.write("\t\t            // 도로명, 지번 주소의 유무에 따라 해당 조합형 주소를 추가한다. \n");
      out.write("\t\t            if (fullRoadAddr !== '') {\n");
      out.write("\t\t                fullRoadAddr += extraRoadAddr;\n");
      out.write("\t\t            }\n");
      out.write("\t\t            // 우편번호와 주소 정보를 해당 필드에 넣는다. \n");
      out.write("\t\t            console.log(data.zonecode);\n");
      out.write("\t\t            console.log(fullRoadAddr);\n");
      out.write("\t\t            /* var a = console.log(data.zonecode); \n");
      out.write("\t\t            var b = console.log(fullRoadAddr); \n");
      out.write("\t\t            if(a == null || b = null){ \n");
      out.write("\t\t                alert(\"주소를 확인하세요.\"); return false; }\n");
      out.write("\t\t                 */\n");
      out.write("\t\t            $(\"input[name=member_zipcode]\").val(data.zonecode);\n");
      out.write("\t\t            $(\"input[name=member_firstaddr]\").val(fullRoadAddr);\n");
      out.write("\t\t            document.getElementById('member_zipcode').value = data.zonecode;\n");
      out.write("\t\t            //5자리 새우편번호 사용 \n");
      out.write("\t\t            document.getElementById('member_firstaddr').value = fullRoadAddr;\n");
      out.write("\t\t            //document.getElementById('member_detailaddress').value = data.jibunAddress; \n");
      out.write("\t\t        }\n");
      out.write("\t\t    }).open();\n");
      out.write("\t\t}\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write('\n');
      out.write('	');
      out.write('\n');
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
	response.setContentType("text/html; charset=UTF-8");

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>모달 레이아웃</title>\n");
      out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"resources/css/insertdonation.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<!-- 팝업 시작 -->\n");
      out.write("\t<div class=\"donation_popup\">\n");
      out.write("\t\t<h2>결제 정보 입력</h2>\n");
      out.write("\t\t<div class=\"donation_popup_body\">\n");
      out.write("\t\t\t<strong class=\"donation_logo_pay\"> <img\n");
      out.write("\t\t\t\tsrc=\"//t1.daumcdn.net/kakaopay/tesla/20181010/pg_web/images/logo_pay.png\"\n");
      out.write("\t\t\t\tclass=\"donation_logo_img\" alt=\"카카오페이\">\n");
      out.write("\t\t\t</strong>\n");
      out.write("\t\t\t<p class=\"donation_desc_payask\">\n");
      out.write("\t\t\t\t결제요청 메시지 전송을 위해<br>아래 정보를 입력해주세요.\n");
      out.write("\t\t\t</p>\n");
      out.write("\t\t\t<input type=\"hidden\" id=\"donation_input_hidden\" name=\"member_no\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t\t<table id=\"donation_table\">\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th class=\"donation_ask\">성명</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"donation_input\"><input class=\"donation_text_color\" type=\"text\"\n");
      out.write("\t\t\t\t\t\tname=\"donor\" placeholder=\"예) 홍길동\" style=\"color: #000000;\" /></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<th class=\"donation_ask\">후원금액</th>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"donation_input\"><input class=\"donation_text_color\" type=\"text\"\n");
      out.write("\t\t\t\t\t\tname=\"donation\"\n");
      out.write("\t\t\t\t\t\toninput=\"this.value = this.value.replace(/[^0-9.]/g,'').replace(/(^0+)/g,'');\"\n");
      out.write("\t\t\t\t\t\tplaceholder=\"예) 1,000 &#10140 1000\" style=\"color: #000000;\" /></td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"donation_submit\">\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" name=\"donation_btn\" value=\"입력확인\" style=\"cursor: pointer;\" />\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</table>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<a href=\"#none\" class=\"donation_close\"> <img\n");
      out.write("\t\t\tsrc=\"//t1.daumcdn.net/kakaopay/tesla/20181010/pg_web/images/ico_close.png\"\n");
      out.write("\t\t\tclass=\"donation_close_btn\" alt=\"닫기\">\n");
      out.write("\t\t</a>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"donation_background\"></div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"https://code.jquery.com/jquery-3.5.1.min.js\"></script>\n");
      out.write("\t<!-- \t아임포트import -->\n");
      out.write("\t<script type=\"text/javascript\"\n");
      out.write("\t\tsrc=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\n");
      out.write("\t<script type=\"text/javascript\">\n");
      out.write("// \t\t클릭시 팝업\n");
      out.write("\t\t$(\"#btn_donation\").click(function() {\n");
      out.write("\t\t\t$(\".donation_popup\").show();\n");
      out.write("\t\t\t$(\".donation_background\").show();\n");
      out.write(" \t\t});\n");
      out.write("\t\t$(\".donation_close>img\").click(function() {\n");
      out.write("\t\t\t$(\".donation_popup\").hide();\n");
      out.write("\t\t\t$(\".donation_background\").hide();\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("// \t\t아임포트api(kakao)\n");
      out.write("\t\t$(\".donation_submit>input\").click(function(){\n");
      out.write("\t\t\t$(\".donation_popup\").hide();\n");
      out.write("\t\t\t$(\".donation_background\").hide();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tvar IMP = window.IMP; // 생략가능\n");
      out.write("\t\t\tIMP.init('imp33221017'); // 'iamport' 대신 부여받은 \"가맹점 식별코드\"를 사용\n");
      out.write("\n");
      out.write("\t\t\tIMP.request_pay({\n");
      out.write("\t\t\t\tpg : 'kakaopay',\n");
      out.write("\t\t\t\tpay_method : 'card',\n");
      out.write("\t\t\t    merchant_uid : 'merchant_' + new Date().getTime(),\n");
      out.write("\t\t\t    name : '후원금',\t\t//결제할 상품?의 명칭\n");
      out.write("\t\t\t    amount : $(\"input[name='donation']\").val(),\n");
      out.write("\t\t\t    buyer_name : $(\"input[name='donor']\").val(),\n");
      out.write("\t\t\t}, function(rsp) {\n");
      out.write("\t\t\t    if ( rsp.success ) {\n");
      out.write("\t\t\t        var msg = '결제가 완료되었습니다.\\n';\n");
      out.write("\t\t\t        console.log(rsp);\n");
      out.write("\t\t\t        msg += rsp.name + '\\n';\n");
      out.write("\t\t\t        msg += '후원자 성명 : ' + rsp.buyer_name + '\\n';\n");
      out.write("\t\t\t        msg += '결제 금액 : ' + rsp.paid_amount + '원';\n");
      out.write("\t\t\t    } else {\n");
      out.write("\t\t\t        var msg = '결제에 실패하였습니다.';\n");
      out.write("\t\t\t        msg += '에러내용 : ' + rsp.error_msg;\n");
      out.write("\t\t\t    }\n");
      out.write("\t\t\t    alert(msg);\n");
      out.write("\t\t\t    $.ajax({\n");
      out.write("\t\t\t\t\ttype: \"POST\",\n");
      out.write("\t\t\t\t\turl: \"insertdonation.do\",\n");
      out.write("\t\t\t\t\tdata: {\n");
      out.write("\t\t\t\t\t\t\"member_no\" : $(\"#donation_input_hidden\").val(),\n");
      out.write("\t\t\t\t\t\t\"donation\" : $(\"input[name='donation']\").val()\n");
      out.write("\t\t\t\t\t\t},\n");
      out.write("\t\t\t\t\tsuccess: function(msg) {\n");
      out.write("\t\t\t\t\t\tconsole.log(msg);\n");
      out.write("\t\t\t\t\t\tconsole.log('값 전달 성공');\n");
      out.write("\t\t\t\t\t}, error: function() {\n");
      out.write("\t\t\t\t\t\tconsole.log('값 전달 실패')\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t});\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</script>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\t\n");
      out.write("\t<script src=\"resources/js/header.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/frienddetail.css\"/>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div id=\"section\">\n");
      out.write("\t<div id=\"profile-section\">\n");
      out.write("\t<div id=\"main-container\">\n");
      out.write("\t\t<div id=\"mypage-photo\">\n");
      out.write("\t\t\t<div id =\"mypage-profileimg\">\n");
      out.write("\t\t\t\t<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div>\n");
      out.write("\t\t\t\t<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h1>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div id=\"mypage-navbar\">\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t<li><a id=\"board\" href=\"\">게시글</a></li>\n");
      out.write("\t\t\t\t<li><a id =\"friends\" href=\"\">친구</a></li>\n");
      out.write("\t\t\t\t<li><a id=\"food\" href=\"\">식단</a></li>\n");
      out.write("\t\t\t\t<li><a id=\"exercise\" href=\"\">운동</a></li>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t<h1>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("의 페이지 입니다.</h1>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction friendRequest(member_no){\n");
      out.write("\t\tvar friend_no = ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("\t\tvar friendrequest = {\n");
      out.write("\t\t\t\tmember_no : member_no,\n");
      out.write("\t\t\t\tfriend_no : friend_no\n");
      out.write("\t\t};\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t\turl : \"friendRequest.do\",\n");
      out.write("\t\t\ttype:\"POST\",\n");
      out.write("\t\t\tdata:JSON.stringify(friendrequest),\n");
      out.write("\t\t\tcontentType : \"application/json\",\n");
      out.write("\t\t\tsuccess : function(msg){\n");
      out.write("\t\t\t \tif(msg.result==1){\n");
      out.write("\t\t\t \t\talert(\"친구요청 되었습니다! 조금만기다려주시면 친구가 수락해주겠죠?!\");\n");
      out.write("\t\t\t \t}else{\n");
      out.write("\t\t\t \t\talert(\"실패..\")\n");
      out.write("\t\t\t \t}\n");
      out.write("\t\t\t},error: function(err){\n");
      out.write("\t\t\t\tconsole.log(err);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t});\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /WEB-INF/views/frienddetail.jsp(36,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${res eq 1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<li><button onclick =\"\" class=\"friend\"><i class=\" fab fa-facebook-messenger\"></i>메세지보내기</button>\n");
          out.write("\t\t\t\t\t<button onclick=\"\" class=\"friend\"><i class=\" fas fa-user-minus\"></i>친구차단</button></li>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t<li><button onclick=\"friendRequest(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_no}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(");\" id =\"request-friend\"> <i class=\"fas fa-user-plus\"></i>친구추가</button></li>\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }
}
